# Generated by Django 3.0.8 on 2020-07-22 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='aadhar',
            field=models.ImageField(upload_to='images/aadhar/'),
        ),
        migrations.AlterField(
            model_name='info',
            name='bankst',
            field=models.ImageField(upload_to='images/bankst/'),
        ),
        migrations.AlterField(
            model_name='info',
            name='pancard',
            field=models.ImageField(upload_to='images/pancard/'),
        ),
        migrations.AlterField(
            model_name='info',
            name='photo',
            field=models.ImageField(upload_to='images/photo/'),
        ),
    ]
